### ISSUE TITLE
serial port access

### ISSUE THREAD

**Issue by gadieichhorn** [DieterReuter/workshop-raspberrypi-64bit-os#2]
The 64 bit image so much faster, thank you!

I have an issue accessing the serial port from docker that works on the standard 32 bit image.
is there something missing on this image or a way to overcome this issue?

I use java  jssc lib  to access serial port (OSGi karaf). I have some temperature sensors I want to read from. I can access them from minicom on the 64 bit image but not from java code in the docker contsainer (this works on the 32 bit hypriot image).

from docker I tryed to give access to the container in different ways but they all get same error and the port is never opened.

here are the optioned I tried:
* -- privileged
* --device=/dev/ttyUSB0
* --devide=/dev/ttyUSB0:/dev/ttyUSB0

```
docker run -i --priviledge --devide=/dev/ttyUSB0:/dev/ttyUSB0 project/image:tag
```
Any suggestions?
thanks in advance.

**Comment by DieterReuter** [comment]
@gadieichhorn Did you tried to disable the UART console first? I think this must be done, before using the UART port for other applications.

**Comment by DieterReuter** [comment]
Close due to inactivity.
